{
 "title": "Visual TOM Monitoring",
 "tags": [
  "VTOM",
  "Monitoring",
  "templates"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Environments",
    "query": "SELECT vtname as \"Environments\"\nFROM vt_core_environments"
   },
   {
    "name": "Applications",
    "query": "SELECT vt_core_applications.vtname AS \"Application\"\nFROM vt_core_applications\nJOIN vt_core_environments ON vt_core_applications.vtenvsid = vt_core_environments.vtsid\nWHERE vt_core_environments.vtname = $Environments"
   },
   { "name": "vtom_server_name", "query": "TOBEDEFINED" },
   { "name": "vitc_server_name", "query": "TOBEDEFINED" },
   { "name": "vitc_token", "query": "TOBEDEFINED" },
   { "name": "splunk_server_name", "label": "Splunk server name", "query": "TOBEDEFINED" }
  ]
 },
 "panels": [
  {
   "title": "Agents monitoring",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT  vtid,\r\n  vtname \"Agent name\", vthostname \"Hostname\",\r\n  CASE vtbdaemonstatus\r\n    WHEN 0 THEN '⁉️ Undetermined'\r\n    WHEN 0 THEN '♻️ Check'\r\n    WHEN 4 THEN '⚠️ Network error'\r\n    WHEN 8 THEN '⛔ Stopped'\r\n    WHEN 16 THEN '✅ Running'\r\n    WHEN 32 THEN '⏸️ Suspended'\r\n    END \"Agent status\",\r\n      CASE vtmanagerstatus\r\n    WHEN 0 THEN '⁉️ Undetermined'\r\n    WHEN 0 THEN '♻️ Check'\r\n    WHEN 4 THEN '⚠️ Network error'\r\n    WHEN 8 THEN '⛔ Stopped'\r\n    WHEN 16 THEN '✅ Running'\r\n    WHEN 32 THEN '⏸️ Suspended'\r\n    END \"Manager status\"\r\n    FROM\r\n      vt_core_hosts"
    }
   ]
  },
  {
   "title": "Environments monitoring",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  vtname as \"Environment\",\r\n  CASE\r\n    WHEN vtenginepid = 0 THEN 'Stopped 🔴'\r\n    WHEN vtenginepid <> 0 THEN 'Running 🟢'\r\n  END \"Status\",\r\n    CASE\r\n    WHEN vtenginepid = 0 THEN 'Start'\r\n    WHEN vtenginepid <> 0 THEN 'Stop'\r\nEND \"Action\"\r\nFROM\r\n  vt_core_environments\r\nWHERE\r\n  CASE\r\n    WHEN \r\n      $Environments <> 'all' THEN vt_core_environments.vtname = $Environments\r\n    ELSE \r\n      TRUE\r\n  END"
    }
   ]
  },
  {
   "title": "Number of errors per day",
   "type": "barchart",
   "description": "Threshold is avg for last 30 days",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  --vtenvname as Environnement ,\r\n  vtexpdatevalue::date as Day,\r\n  '\"year\":'||DATE_PART('year',vtexpdatevalue)||',\"month\":'||DATE_PART('month',vtexpdatevalue)\r\n  ||',\"day\":'||DATE_PART('day',vtexpdatevalue) as Filter ,\r\nCASE \r\n    WHEN $Environments <> 'all' THEN\r\n      CASE WHEN $Applications <> 'all' THEN \r\n       '&filters={\"condition\":\"AND\",\"filters\":{\"environments\":{\"name\":{\"comparator\":\"EQUALS\",\"valueToCompare\":\"'||$Environments||'\"}},\"applications\":{\"name\":{\"comparator\":\"EQUALS\",\"valueToCompare\":\"'||$Applications||'\"}}}}'\r\n      ELSE\r\n        '&filters={\"condition\":\"AND\",\"filters\":{\"environments\":{\"name\":{\"comparator\":\"EQUALS\",\"valueToCompare\":\"'||$Environments||'\"}}}}'\r\n      END\r\n    ELSE\r\n      ''\r\n    END filterEnvtApp,\r\n  count(*) as Nombre\r\nFROM vt_stats_job \r\nWHERE CASE \r\n    WHEN $Environments <> 'all' THEN\r\n      CASE WHEN $Applications <> 'all' THEN \r\n        vtstatus=4 AND vtexpdatevalue >= CURRENT_DATE - INTERVAL '30 days' AND vtenvname = $Environments AND vtapplname = $Applications \r\n      ELSE\r\n        vtstatus=4 AND vtexpdatevalue >= CURRENT_DATE - INTERVAL '30 days' AND vtenvname = $Environments\r\n      END\r\n    ELSE\r\n      vtstatus=4 AND vtexpdatevalue >= CURRENT_DATE - INTERVAL '30 days'\r\n    END\r\nGROUP BY --vtenvname,\r\n vtexpdatevalue\r\n order by to_char(vtexpdatevalue,'YYYYMMDD')"
    },
    {
     "rawSql": "SELECT \r\n  count(*)/30 as AvgErrors\r\nFROM vt_stats_job \r\nWHERE CASE \r\n    WHEN $Environments <> 'all' THEN\r\n      CASE WHEN $Applications <> 'all' THEN \r\n        vtstatus=4 AND vtexpdatevalue >= CURRENT_DATE - INTERVAL '30 days' AND vtenvname = $Environments AND vtapplname = $Applications \r\n      ELSE\r\n        vtstatus=4 AND vtexpdatevalue >= CURRENT_DATE - INTERVAL '30 days' AND vtenvname = $Environments\r\n      END\r\n    ELSE\r\n      vtstatus=4 AND vtexpdatevalue >= CURRENT_DATE - INTERVAL '30 days'\r\n    END"
    }
   ]
  },
  {
   "title": "Blocked or late dates",
   "type": "table",
   "description": "Blocked and late dates",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT CASE WHEN COUNT(vtjobsid)>0 THEN '🔒Blocked' ELSE '' END || CASE WHEN (left(text(to_timestamp(vtvalue/1000000)),10)::date!=CURRENT_DATE AND (vtswitchtime * interval '1 sec'- INTERVAL '24 hours')::time < CURRENT_TIME) THEN '🕒Late' ELSE '' END \"Status\",\r\nLEFT(text(to_timestamp(vtvalue/1000000)),10) \"Value\", vtname \"Date\", (vtswitchtime * interval '1 sec') \"Switch time\",\r\nCASE vttype WHEN 'A' THEN 'Automatic' WHEN 'S' THEN 'System' ELSE 'Constant' END \"Type\",\r\nCASE vtrecovery WHEN '0' THEN '✔️' ELSE '-' END \"Automatic recovery\", CASE WHEN COUNT(vtjobsid)>0 THEN COUNT(vtjobsid)|| ' Jobs' ELSE '-' END \"Blocking Jobs\", vtid from vt_core_dates dates\r\nLEFT JOIN vt_core_date_blocking_jobs bloc_jobs ON dates.vtid=bloc_jobs.vtdateid\r\nWHERE (left(text(to_timestamp(vtvalue/1000000)),10)::date!=CURRENT_DATE AND (vtswitchtime * interval '1 sec'- INTERVAL '24 hours')::time < CURRENT_TIME)\r\nOR vtjobsid IS NOT NULL\r\nGROUP BY vtid"
    }
   ]
  },
  {
   "title": "Jobs statuses distribution",
   "type": "piechart",
   "description": "Statuses are clickable to access Job's monitoring in XVision",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT vt_core_jobs.vtstatus, COUNT(*)\r\nFROM \r\n  vt_core_jobs\r\n  JOIN vt_core_applications USING (vtappsid)\r\n  JOIN vt_core_environments ON vt_core_applications.vtenvsid = vt_core_environments.vtsid\r\nWHERE\r\n  CASE\r\n    WHEN $Environments <> 'all' THEN \r\n    CASE\r\n      WHEN $Applications <> 'all' THEN \r\n        vt_core_environments.vtname = $Environments AND vt_core_applications.vtname = $Applications\r\n      ELSE \r\n        vt_core_environments.vtname = $Environments\r\n    END\r\n    ELSE \r\n      TRUE\r\n  END\r\n  GROUP BY vt_core_jobs.vtstatus"
    }
   ]
  },
  {
   "title": "Failed jobs",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  vt_core_environments.vtname || '/' || vt_core_applications.vtname || '/' || vt_core_jobs.vtname as \"Jobs\",\r\n  vtmessage as \"Message\",\r\n  vt_core_environments.vtname as Env,\r\n  vt_core_applications.vtname as App,\r\n  vt_core_jobs.vtname as Job, \r\n  CASE\r\n    WHEN vt_core_jobs.vtsubstatus = 0 THEN 'Not taken into account'\r\n    WHEN vt_core_jobs.vtsubstatus = 1 THEN 'Taken into account'\r\n  END \"Mark\",\r\n  '' AS \"Action\"\r\nFROM\r\n  vt_core_jobs\r\n  JOIN vt_core_applications USING (vtappsid)\r\n  JOIN vt_core_environments ON vt_core_applications.vtenvsid = vt_core_environments.vtsid\r\nWHERE\r\n  CASE\r\n    WHEN $Environments <> 'all' THEN CASE\r\n      WHEN $Applications <> 'all' THEN \r\n        vt_core_jobs.vtstatus = '4' AND vt_core_environments.vtname = $Environments AND vt_core_applications.vtname = $Applications\r\n      ELSE \r\n        vt_core_jobs.vtstatus = '4' AND vt_core_environments.vtname = $Environments\r\n    END\r\n    ELSE \r\n      vt_core_jobs.vtstatus = '4'\r\n  END"
    }
   ]
  }
 ]
}